name: nthaka_eco
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.2.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.2
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.4
  pdf: ^3.11.1
  share_plus: ^10.0.2
  mobile_scanner: ^5.2.3
  timezone: ^0.9.4
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/app/
    - assets/fonts/
    - assets/data/
    - assets/model/

  fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans.ttf
      - asset: assets/fonts/OpenSans-Italic.ttf
